
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async killSidecar() : Promise<void> {
    await TAURI_INVOKE("kill_sidecar");
},
async awaitInitialization(events: TAURI_CHANNEL<InitStep>) : Promise<ServerReadyData> {
    return await TAURI_INVOKE("await_initialization", { events });
},
async appendFrontendLog(line: string) : Promise<null> {
    return await TAURI_INVOKE("append_frontend_log", { line });
},
async getDefaultServerUrl() : Promise<string | null> {
    return await TAURI_INVOKE("get_default_server_url");
},
async setDefaultServerUrl(url: string | null) : Promise<null> {
    return await TAURI_INVOKE("set_default_server_url", { url });
},
async windowMinimize() : Promise<null> {
    return await TAURI_INVOKE("window_minimize");
},
async windowMaximize() : Promise<null> {
    return await TAURI_INVOKE("window_maximize");
},
async windowClose() : Promise<null> {
    return await TAURI_INVOKE("window_close");
},
async windowMaximizeToggle() : Promise<null> {
    return await TAURI_INVOKE("window_maximize_toggle");
},
async windowIsMaximized() : Promise<boolean> {
    return await TAURI_INVOKE("window_is_maximized");
},
async windowIsFullscreen() : Promise<boolean> {
    return await TAURI_INVOKE("window_is_fullscreen");
},
async windowToggleFullscreen() : Promise<null> {
    return await TAURI_INVOKE("window_toggle_fullscreen");
},
async windowSetBackgroundColor(color: string) : Promise<null> {
    return await TAURI_INVOKE("window_set_background_color", { color });
},
async openUrl(url: string) : Promise<null> {
    return await TAURI_INVOKE("open_url", { url });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type InitStep = { phase: "server_waiting" } | { phase: "done" }
export type ServerReadyData = { url: string; password: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
