import * as fsp from "node:fs/promises";
import * as path from "node:path";

const MANAGED_BLOCK_START = "<!-- bfloat-managed:start -->";
const MANAGED_BLOCK_END = "<!-- bfloat-managed:end -->";

function normalizeCustomInstructions(custom?: string): string {
  return (custom || "").trim();
}

function buildManagedBlock(custom?: string): string {
  const normalizedCustom = normalizeCustomInstructions(custom);
  const customSection = normalizedCustom
    ? [
        "## Custom Instructions",
        "User-provided instructions (shared across agents):",
        "",
        normalizedCustom,
      ].join("\n")
    : [
        "## Custom Instructions",
        "No custom instructions provided.",
      ].join("\n");

  return [
    MANAGED_BLOCK_START,
    "## Agent Behavior Requirements",
    "- For new projects, always use the `/frontend-design` skill before implementing frontend UI work.",
    "- Treat design-system adaptation as default unless the user explicitly asks for a redesign.",
    "",
    customSection,
    MANAGED_BLOCK_END,
  ].join("\n");
}

export function renderAgentsFile(custom?: string): string {
  return [
    "# AGENTS.md",
    "",
    "This file is managed by Bfloat IDE.",
    "The block below is regenerated by the app and should not be edited manually.",
    "",
    buildManagedBlock(custom),
    "",
  ].join("\n");
}

export function renderClaudeFile(custom?: string): string {
  return [
    "# CLAUDE.md",
    "",
    "This file is managed by Bfloat IDE.",
    "The block below is regenerated by the app and should not be edited manually.",
    "",
    buildManagedBlock(custom),
    "",
  ].join("\n");
}

export async function syncAgentInstructionFiles(
  projectRoot: string,
  custom?: string,
): Promise<string[]> {
  const targets = [
    path.join(projectRoot, "AGENTS.md"),
    path.join(projectRoot, "CLAUDE.md"),
  ];

  await fsp.mkdir(projectRoot, { recursive: true });
  await fsp.writeFile(targets[0], renderAgentsFile(custom), "utf8");
  await fsp.writeFile(targets[1], renderClaudeFile(custom), "utf8");

  return targets;
}
