/**
 * client.ts — Base HTTP client for the Bfloat sidecar API.
 *
 * Wraps @tauri-apps/plugin-http fetch so that all requests:
 *  - Bypass browser CORS restrictions (requests go through the Tauri native layer)
 *  - Include Basic auth credentials automatically
 *  - Serialize/deserialize JSON bodies
 *  - Surface structured errors as `SidecarError` instances
 *
 * Usage:
 *   const client = new HttpClient("http://127.0.0.1:4000", "secret-uuid")
 *   const result = await client.get<{ ok: boolean }>("/health")
 */

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

export class SidecarError extends Error {
  constructor(
    /** HTTP status code, or 0 for network-level failures. */
    public readonly status: number,
    /** Human-readable error message from the server or client. */
    message: string,
    /** Raw response body (may be empty). */
    public readonly body: string = "",
  ) {
    super(message)
    this.name = "SidecarError"
  }
}

// ---------------------------------------------------------------------------
// Request helpers
// ---------------------------------------------------------------------------

export interface RequestOptions {
  /** Additional headers to merge with the default set. */
  headers?: Record<string, string>
  /** Request signal for cancellation. */
  signal?: AbortSignal
}

// ---------------------------------------------------------------------------
// HttpClient
// ---------------------------------------------------------------------------

/**
 * Thin, typed HTTP client that talks to the Bfloat sidecar over localhost.
 *
 * The client lazily imports `@tauri-apps/plugin-http` so that it can be
 * instantiated before the Tauri webview plugin chain is fully initialised.
 * Actual network calls are deferred until the first method invocation.
 */
export class HttpClient {
  readonly baseUrl: string
  /** Base64-encoded "bfloat:<password>" for the Authorization header. */
  private readonly authHeader: string

  /**
   * @param baseUrl  Full origin of the sidecar, e.g. "http://127.0.0.1:4000".
   *                 Trailing slashes are stripped.
   * @param password The UUID password generated by the Tauri backend.
   *                 Pass null/undefined when connecting to a custom server
   *                 that has no auth requirement.
   */
  constructor(baseUrl: string, password: string | null | undefined) {
    this.baseUrl = baseUrl.replace(/\/+$/, "")

    if (password) {
      this.authHeader = "Basic " + btoa(`bfloat:${password}`)
    } else {
      this.authHeader = ""
    }
  }

  // --------------------------------------------------------------------------
  // Public HTTP verbs
  // --------------------------------------------------------------------------

  /** Perform a GET request and parse the JSON response. */
  async get<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("GET", path, undefined, options)
  }

  /** Perform a POST request with a JSON body and parse the JSON response. */
  async post<T>(
    path: string,
    body?: unknown,
    options?: RequestOptions,
  ): Promise<T> {
    return this.request<T>("POST", path, body, options)
  }

  /** Perform a PUT request with a JSON body and parse the JSON response. */
  async put<T>(
    path: string,
    body?: unknown,
    options?: RequestOptions,
  ): Promise<T> {
    return this.request<T>("PUT", path, body, options)
  }

  /** Perform a PATCH request with a JSON body and parse the JSON response. */
  async patch<T>(
    path: string,
    body?: unknown,
    options?: RequestOptions,
  ): Promise<T> {
    return this.request<T>("PATCH", path, body, options)
  }

  /** Perform a DELETE request and parse the JSON response. */
  async delete<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("DELETE", path, undefined, options)
  }

  // --------------------------------------------------------------------------
  // WebSocket URL builder
  // --------------------------------------------------------------------------

  /**
   * Construct a fully-qualified WebSocket URL for the given sidecar path.
   *
   * Converts "http://" → "ws://" and "https://" → "wss://" automatically.
   * The password is passed as a query parameter because browser WebSocket
   * constructors cannot set arbitrary request headers.
   *
   * @example
   *   client.wsUrl("/terminal/abc/stream")
   *   // → "ws://127.0.0.1:4000/terminal/abc/stream?password=xxx"
   */
  wsUrl(path: string): string {
    const wsBase = this.baseUrl
      .replace(/^http:\/\//, "ws://")
      .replace(/^https:\/\//, "wss://")

    const normalised = path.startsWith("/") ? path : `/${path}`

    if (!this.authHeader) {
      return `${wsBase}${normalised}`
    }

    // Extract the raw password from the Base64 "bfloat:<password>" credential.
    const decoded = atob(this.authHeader.slice("Basic ".length))
    const password = decoded.slice("bfloat:".length)

    const sep = normalised.includes("?") ? "&" : "?"
    return `${wsBase}${normalised}${sep}password=${encodeURIComponent(password)}`
  }

  // --------------------------------------------------------------------------
  // Internal implementation
  // --------------------------------------------------------------------------

  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
    options?: RequestOptions,
  ): Promise<T> {
    // Lazy-import the Tauri HTTP plugin to avoid loading it before the Tauri
    // runtime is ready.
    const { fetch: tauriFetch } = await import("@tauri-apps/plugin-http")

    const url = `${this.baseUrl}${path.startsWith("/") ? path : `/${path}`}`

    const headers: Record<string, string> = {
      Accept: "application/json",
      ...options?.headers,
    }

    if (this.authHeader) {
      headers["Authorization"] = this.authHeader
    }

    let serialisedBody: string | undefined
    if (body !== undefined) {
      headers["Content-Type"] = "application/json"
      serialisedBody = JSON.stringify(body)
    }

    let response: Response
    try {
      response = await tauriFetch(url, {
        method,
        headers,
        body: serialisedBody,
        signal: options?.signal,
      })
    } catch (err) {
      throw new SidecarError(
        0,
        `Network error contacting sidecar: ${err instanceof Error ? err.message : String(err)}`,
      )
    }

    const text = await response.text()

    if (!response.ok) {
      // Try to extract a structured error message from the response body.
      let message = `Sidecar returned ${response.status}`
      try {
        const parsed = JSON.parse(text)
        if (typeof parsed?.error === "string") message = parsed.error
        else if (typeof parsed?.message === "string") message = parsed.message
      } catch {
        if (text) message = text
      }
      throw new SidecarError(response.status, message, text)
    }

    // 204 No Content and similar empty responses.
    if (!text) {
      return undefined as T
    }

    try {
      return JSON.parse(text) as T
    } catch {
      throw new SidecarError(
        response.status,
        `Failed to parse sidecar response as JSON: ${text.slice(0, 120)}`,
        text,
      )
    }
  }
}
