/**
 * index.ts — SidecarApi: the unified API client for the Bfloat sidecar.
 *
 * The SidecarApi class wires together all domain-specific sub-clients
 * (terminal, filesystem, agent) behind a single authenticated HTTP client.
 *
 * It is initialised once — after the Tauri `await_initialization` command
 * resolves — and then accessed via the module-level `getSidecarApi()` /
 * `getSidecarApiSync()` helpers (mirroring the `getPlatform()` pattern used
 * elsewhere in the desktop package).
 *
 * Usage:
 *
 *   // In your app boot sequence (e.g. ServerGate in entry.tsx):
 *   import { initialiseSidecarApi, getSidecarApi } from "./api"
 *
 *   const { url, password } = await invoke("await_initialization", ...)
 *   initialiseSidecarApi(url, password)
 *
 *   // Anywhere else in the renderer:
 *   const api = getSidecarApiSync()
 *   const result = await api.terminal.create("my-terminal", "/home/user/project")
 *
 * Migration note:
 *   The sub-clients expose the same logical methods as the Electron conveyor
 *   APIs so that existing renderer code needs only minimal changes:
 *
 *     // Before (Electron):
 *     window.conveyor.terminal.create(id, cwd)
 *     window.conveyor.filesystem.readFile(path)
 *     window.conveyor.aiAgent.createSession(opts)
 *
 *     // After (Tauri):
 *     const api = getSidecarApiSync()
 *     api.terminal.create(id, cwd)
 *     api.filesystem.readFile(path)
 *     api.agent.createSession(opts)
 */

import { HttpClient } from "./client"
import { TerminalApi } from "./terminal"
import { FilesystemApi } from "./filesystem"
import { AgentApi } from "./agent"

// Re-export all public symbols so consumers can import everything from "./api".
export { HttpClient } from "./client"
export { SidecarWebSocket } from "./websocket"
export { TerminalApi } from "./terminal"
export { FilesystemApi } from "./filesystem"
export { AgentApi } from "./agent"
export { SidecarError } from "./client"

export type { RequestOptions } from "./client"
export type { SidecarWebSocketOptions } from "./websocket"
export type {
  TerminalCreateOptions,
  TerminalCreateResult,
  TerminalWriteResult,
  TerminalResizeResult,
  TerminalKillResult,
  TerminalSession,
  TerminalListResult,
  CheckPortResult,
  FindPortResult,
  TerminalStreamMessage,
  TerminalStreamCommand,
} from "./terminal"
export type {
  FileEntry,
  FileStat,
  DirEntry,
  OperationResult as FilesystemOperationResult,
  ReadResult,
  ExistsResult,
  ReaddirResult,
  StatResult,
  CreateTempDirResult,
} from "./filesystem"
export type {
  ProviderId,
  PermissionMode,
  MessageType,
  BackgroundSessionStatus,
  SessionStatus,
  AgentModel,
  ProviderInfo,
  SessionOptions,
  ToolCallContent,
  ToolResultContent,
  ErrorContent,
  InitContent,
  DoneContent,
  AgentMessage,
  SessionState,
  SessionInfo,
  BackgroundSessionData,
  BackgroundSessionInfo,
  CreateSessionResult,
  PromptResult,
  OperationResult as AgentOperationResult,
  BackgroundSessionResult,
  BackgroundMessagesResult,
  SessionMessageBlock,
  SessionMessageData,
  ReadSessionResult,
  ListSessionsResult,
  AgentStreamMessage,
} from "./agent"

// ---------------------------------------------------------------------------
// SidecarApi
// ---------------------------------------------------------------------------

/**
 * The unified API client for the Bfloat sidecar.
 *
 * Instantiate once with the URL and password returned by `await_initialization`,
 * then use the sub-client properties to make requests.
 */
export class SidecarApi {
  /** The underlying HTTP client.  Exposed for advanced usage (e.g. custom routes). */
  readonly http: HttpClient

  /** Terminal session management and PTY I/O streaming. */
  readonly terminal: TerminalApi

  /** Filesystem operations (read, write, stat, mkdir, …). */
  readonly filesystem: FilesystemApi

  /** AI agent session management and streaming responses. */
  readonly agent: AgentApi

  /**
   * @param url       Full base URL of the sidecar (e.g. "http://127.0.0.1:4000").
   * @param password  The UUID password generated by the Tauri backend.
   *                  Pass null when connecting to an external server without auth.
   */
  constructor(url: string, password: string | null | undefined) {
    this.http = new HttpClient(url, password)
    this.terminal = new TerminalApi(this.http)
    this.filesystem = new FilesystemApi(this.http)
    this.agent = new AgentApi(this.http)
  }
}

// ---------------------------------------------------------------------------
// Module-level singleton
// ---------------------------------------------------------------------------

let _api: SidecarApi | null = null

/**
 * Initialise the module-level SidecarApi singleton.
 *
 * This must be called exactly once, after the Tauri `await_initialization`
 * command resolves and before any API calls are made.
 *
 * Calling this a second time replaces the existing instance (useful in tests).
 *
 * @param url       Sidecar base URL from `ServerReadyData.url`.
 * @param password  Sidecar password from `ServerReadyData.password`.
 */
export function initialiseSidecarApi(
  url: string,
  password: string | null | undefined,
): SidecarApi {
  _api = new SidecarApi(url, password)
  return _api
}

/**
 * Return the module-level SidecarApi singleton.
 *
 * Throws `Error` if `initialiseSidecarApi()` has not been called yet.
 * Use this in hot paths where async overhead is undesirable.
 *
 * @throws {Error} When called before `initialiseSidecarApi()`.
 */
export function getSidecarApiSync(): SidecarApi {
  if (!_api) {
    throw new Error(
      "SidecarApi has not been initialised yet. Call initialiseSidecarApi() first.",
    )
  }
  return _api
}

/**
 * Return the module-level SidecarApi singleton asynchronously.
 *
 * Polls until the singleton is available, making it safe to call immediately
 * after mounting the React tree (before `initialiseSidecarApi()` completes).
 *
 * The poll interval is 20 ms with a 10-second timeout.
 *
 * @throws {Error} When the singleton is not initialised within 10 seconds.
 */
export async function getSidecarApi(): Promise<SidecarApi> {
  if (_api) return _api

  const POLL_INTERVAL = 20
  const TIMEOUT = 10_000
  const start = Date.now()

  return new Promise<SidecarApi>((resolve, reject) => {
    const interval = setInterval(() => {
      if (_api) {
        clearInterval(interval)
        resolve(_api)
        return
      }

      if (Date.now() - start > TIMEOUT) {
        clearInterval(interval)
        reject(
          new Error(
            "Timed out waiting for SidecarApi to be initialised. " +
              "Ensure initialiseSidecarApi() is called during app boot.",
          ),
        )
      }
    }, POLL_INTERVAL)
  })
}
